let constants = {

PRODUCT_META_DATA : 'PRODUCT_META_DATA',
META_DATA : 'META_DATA',
SAVE_PRODUCT_META_DATA : 'SAVE_PRODUCT_META_DATA',
AUTO_COMPLETE : 'AUTO_COMPLETE',
PRODUCT_META_DATA_ERROR : 'PRODUCT_META_DATA_ERROR',
META_DATA_ERROR : 'META_DATA_ERROR',
SAVE_PRODUCT_META_DATA_ERROR : 'SAVE_PRODUCT_META_DATA_ERROR',
AUTOCOMPLETE_DATA_ERROR : 'AUTOCOMPLETE_DATA_ERROR'
}
module.exports = constants;
