const searchLibraryConstants = {
    AUTO_COMPLETE : 'AUTO_COMPLETE',
    UPDATE_SEARCH_VALUE : 'UPDATE_SEARCH_VALUE',
    SAVED_SEARCH_VALUE : 'SAVED_SEARCH_VALUE',
    CHECKED_SAVED_SEARCH_VALUE: 'CHECKED_SAVED_SEARCH_VALUE',
    GET_ASSERTS_DATA: 'GET_ASSERTS_DATA',
    SEARCH_DISPLAY_ASSETS: 'SEARCH_DISPLAY_ASSETS',
    UPDATE_CHECKBOX_VALUE: 'UPDATE_CHECKBOX_VALUE',
    SEARCH_BUTTON_VISIBILITY: 'SEARCH_BUTTON_VISIBILITY'
}

module.exports = searchLibraryConstants;
