const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
const UPDATE_ALL_PRODUCT = 'UPDATE_ALL_PRODUCT';
const LOAD_ALL_PRODUCT_BEGIN = 'LOAD_ALL_PRODUCT_BEGIN';
const ERR_ALL_PRODUCT = 'ERR_ALL_PRODUCT'


export const constant  = {
  UPDATE_INPUT_VALUE,
  CLEAR_SUGGESTIONS,
  MAYBE_UPDATE_SUGGESTIONS,
  LOAD_SUGGESTIONS_BEGIN,
  UPDATE_ALL_PRODUCT,
  LOAD_ALL_PRODUCT_BEGIN,
  ERR_ALL_PRODUCT
}
